source "https://rubygems.org"

ruby "3.3.10"

gem "rails", "~> 7.2.3"
gem "sqlite3", ">= 1.4"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "httparty"
gem "jbuilder"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]
